env = GDK_SCALE,1
monitor=,preferred,auto,1

input {
  kb_options = caps:escape
  sensitivity = 0.3
  scroll_factor = 1.5
  touchpad {
    natural_scroll = true
    clickfinger_behavior = true
  }
}

# Swap Alt and Super only for the built-in laptop keyboard
device {
  name = at-translated-set-2-keyboard
  kb_options = caps:escape,altwin:swap_alt_win
}

gestures {
  workspace_swipe_use_r = true
  gesture = 3, horizontal, workspace
}

animations {
  enabled = 0
}

general {
  col.active_border = rgba(ffffffee)
}

# Speed up mouse scroll in Ghostty
windowrule = match:class com.mitchellh.ghostty, scroll_mouse 4

unbind = SUPER, J
unbind = SUPER, K

bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, J, Move focus down, movefocus, d
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, L, Move focus right, movefocus, r

unbind = SUPER SHIFT, G
bindd = SUPER SHIFT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
